apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudhunter
  namespace: cloudhunter
subjects:
- kind: ServiceAccount
  name: cloudhunter
  namespace: cloudhunter
roleRef:
  kind: ClusterRole
  name: cloudhunter 
  apiGroup: rbac.authorization.k8s.io
