resources:
- cloudhunter-secret.yaml
- cloudhunter-service.yaml
- cloudhunter-service-account.yaml
- cloudhunter-cluster-role.yaml
- cloudhunter-cluster-role-binding.yaml
- cloudhunter-deployment.yaml
- cloudhunter-namespace.yaml
- cloudhunter-route.yaml
