apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pacman
  namespace: pacman
spec:
  host: pacman-pacman.apps.cluster-8392.8392.sandbox116.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: pacman
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
