apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mongo
  namespace: mongo
spec:
  selector:
    matchExpressions:
    - key: name  
      operator: In
      values:
      - mongo 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
