apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mongo-cluster2                           
  namespace: mongo
  labels:
    name: mongo
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-6-assets/overlays/cluster2
spec:
  channel:  mongo/mongochannel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster2
