apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: mongo
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
