apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: web-app-cluster3
  namespace: web-app
  labels:
    deployment: hello
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-5-assets/overlays/cluster3
spec:
  channel:  web-app/web-app-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster3
