apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cloudhunter
  namespace: cloudhunter
spec:
  selector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - cloudhunter
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
