apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman
spec:
  selector:
    matchExpressions:
    - key: name  
      operator: In
      values:
      - pacman 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
