apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-cluster3
  namespace: pacman
  labels:
    name: pacman
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-7-assets/overlays/cluster3
spec:
  channel:  pacman/pacmanchannel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: pacmancluster3
