apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cloudhunter-cluster3
  namespace: cloudhunter
  labels:
    name: cloudhunter
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-7-assets/overlays/cluster3
spec:
  channel:  cloudhunter/cloudhunterchannel
  placement:
    placementRef:
      kind: PlacementRule
      name: cloudhuntercluster3
